### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by Kondra007** [blackgear/ingrex_lib#4]
```python
  File "C:\Python34\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1557-1563: character maps to <undefined>
```
I guess this problem is from Python 2 parts of code. But where is it?

Upd: test.py works fine in Python 2, but comm.py shows this error in both 2 and 3

**Comment by blackgear** [comment]
It seems like a encoding problem, can you provide more information about your code, system and all the error messages?

**Comment by Kondra007** [comment]
Python 3.4.3, code is fully yours

```python
C:\Python27\python.exe "E:/Python Projects/telegram-ingress-bot/comm.py"
Traceback (most recent call last):
  File "E:/Python Projects/telegram-ingress-bot/comm.py", line 31, in <module>
    main()
  File "E:/Python Projects/telegram-ingress-bot/comm.py", line 27, in main
    print(u'{} {}'.format(message.time, message.text))
  File "C:\Python27\lib\encodings\cp1251.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-63: character maps to <undefined>

Process finished with exit code 1
```

The only difference now it that I've added `# -*- coding: utf-8 -*-` to the beginning and hard-coded cookie string

**Comment by blackgear** [comment]
It's problem is caused by cmd.exe. Your cmd.exe is using cp1251 as the default encoding. Then Python try to use cp1251 to encode the string.

See: http://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined to solve your problem, or you can just write the message to a file instead of print it out to skip the encoding problem.

**Comment by Kondra007** [comment]
Yep, works for me in Linux, thank you!
