### ISSUE TITLE
test.py fetches nothing

### ISSUE THREAD

**Issue by ghost** [blackgear/ingrex_lib#9]
Hi, when running test.py i just got a {} back.
comm.py works fine. (I wondered that im able to see messages from Beijing if i was online in germany with my handy)

Id run test.py with python test.py
Did i made sth wrong?

Thanks in advance,
gamecompiler

**Comment by ghost** [comment]
Got it working now, intel.fetch_artifacts() (And the lines above) overwrite the variable result. Its empty because intel.fetch_artifacts() returns nothing.

What kind of coordinates do you use ? I do not understand what format that is.

**Comment by blackgear** [comment]
LngE6 = Longitude * 1E6
LatE6 = Latitude * 1E6
